### ISSUE TITLE
About the license for this model

### ISSUE THREAD

**Issue by PINTO0309** [Aiemu/Zero-DCE-improved#1]
Thank you for sharing your great code. :smiley_cat:

What is the license for this model? I'd like to cite it to the repository I'm working on if possible, but I want to post the license correctly.
https://github.com/PINTO0309/PINTO_model_zoo

Thank you.

**Comment by Aiemu** [comment]
Hi!

This model is implemented based on [Zero-DCE](https://github.com/Li-Chongyi/Zero-DCE). As the original author of Zero-DCE said in [issue #34](https://github.com/Li-Chongyi/Zero-DCE/issues/34), the code is **for academic use only**.

This  repository will also follow this.

**Comment by PINTO0309** [comment]
Thank you!
